default:
  golem_name: kypoliticaldata
  golem_version: 0.0.0.9000
  app_prod: no
  db_name: kypolitics
  db_driver: PostgreSQL Unicode
  db_host: 127.0.0.1
  db_port: 5433
  db_use_keyring: yes
  logo_path: ""
production:
  app_prod: yes
  db_name: kypolitics
  db_driver: PostgreSQL ANSI
  db_host: ""
  db_port: !expr NA
  db_use_keyring: no
  logo_path: /srv/img/logo_crop.png
dev:
  golem_wd: !expr here::here()
  db_name: kypolitics
  db_driver: PostgreSQL Unicode
  db_host: 127.0.0.1
  db_port: 5433
  db_use_keyring: yes
  logo_path: ""
